spring:
  config:
    activate:
      on-profile:
        dev
  datasource:
    url: jdbc:postgresql://localhost:5432/nps
    driverClassName: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema-postgre.sql
      data-locations: classpath:db/data.sql
logging:
  level:
    org:
      springframework.orm.jpa: DEBUG
